### ISSUE TITLE
CSS/Form Render Issue

### ISSUE THREAD

**Issue by JJediny** [StackStorm/st2web#333]
> Cross-post just to flag - please close here if already a none issue:
> https://github.com/StackStorm/showcase-ansible-chatops/issues/12

Dropdowns on Form fields has the default css attribute `.st2-auto-form__field option` value was `color: white` wasn't sure if this was an already tweaked fix upstream. 

![image](https://cloud.githubusercontent.com/assets/6350035/20050127/6d070bae-a495-11e6-8f7c-910fc3804595.png)

![image](https://cloud.githubusercontent.com/assets/6350035/20050140/7bab9ae4-a495-11e6-8195-e5e30d525c28.png)

*From daily release of Chrome .deb on Ubuntu 14.04

**Comment by enykeev** [comment]
A very strange issue I was only able to reproduce to some degree in Firefox.

**Comment by LindsayHill** [comment]
Seems to be same issue as https://github.com/StackStorm/st2web/issues/355, which should be addressed by https://github.com/StackStorm/st2web/issues/356

**Comment by bigmstone** [comment]
Closed because #356 is merged. Please reopen if problem persists.
