### ISSUE TITLE
Potential security issues in outdated dependencies

### ISSUE THREAD

**Issue by armab** [StackStorm/st2web#746]
> Warning! `st2web` needs help and React/UI maintainer!

`st2web` has a lot of security warnings in its outdated npm dependencies located in https://github.com/StackStorm/st2web/blob/master/yarn.lock

(https://github.com/StackStorm/st2web/network/alerts)

![](https://i.imgur.com/4gNZnHF.png)

We'll need someone experienced in React/UI/Javascript to update them, making sure `st2web` functionality/tests are still working as before.

We'll probably need to get another round of manual/UI testing searching for regressions once the patching is done.

**Comment by guzzijones** [comment]
I am running an `npm update` now.  I see the deprecated warnings. I will take a stab at this.

**Comment by guzzijones** [comment]
I am working on removing cryptiles and changing to @hapi/cryptiles in each modules.

**Comment by punkrokk** [comment]
Let @bgaeddert know your progress, he was working on this also

**Comment by guzzijones** [comment]
@bgaeddert please pop in here if you are working on another.

**Comment by punkrokk** [comment]
@armab I think we addressed this with https://github.com/StackStorm/st2web/pull/757, do you agree?

**Comment by armab** [comment]
@punkrokk I'd say partially. While #757 removes some unused dependencies, there is no PR which updates existing dependencies.

Currently https://github.com/StackStorm/st2web/network/alerts still shows some `25` issues, which is an improvement comparing to `36` before.

**Comment by punkrokk** [comment]
@armab This PR: https://github.com/StackStorm/st2web/pull/794 addressed all of this. If you approve, please close.

**Comment by armab** [comment]
I guess we need to merge the #794 first to understand if https://github.com/StackStorm/st2web/network/alerts is clear.
Do we have someone who can review that PR?

**Comment by nmaludy** [comment]
These issues have been remediated and only development dependencies are outlying as of the 3.3.0 release!
